proyecto_final/Ventas/urls.py
from django.contrib import admin
from django.urls import path

from .views.base.views import Base
from .views.linea.views import ClienteListView
from .views.productos.views import ProductosListView
from .views.postulante.views import PostulanteCreateViews
app_name="Ventas"
urlpatterns = [

    path('base', Base.as_view(), name="base"),
    path('cliente', ClienteListView.as_view(), name='cliente'),
    path('productos',ProductosListView.as_view(),name='productos'),
    path('postulante',PostulanteCreateViews.as_view(),name='postulante')

]

proyecto_final/proyecto_final/urls.py
from django.urls import path,include
from .views import Principal,Linea,Productos
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Principal.as_view(),name="menu"),
    path('linea/',Linea.as_view(),name="linea"),
    path('producto',Productos.as_view(),name="producto"),

    path('sa/',include('Ventas.urls'))
]

proyecto_final/templates/footer.html
{% load static %}
<footer class="footer">
  <div class="footer__addr">
    <h1 class="footer__logo"> Distribudora&#8594;{{ nombre }}</h1>

    <h2>contacto</h2>

    <address>
      <a class="navbar-brand aim" href="#">
          LLAME AL
          {{ contacto }}
         <img src="{% static 'img/contacto.png' %}" alt="" width="50" height="50">
        </a>
        <br>

    </address>

    <address>
      <a class="navbar-brand aim" href="#">
          Correo
          {{ correo }}
        </a>
        <br>

      <a class="footer__btn" href="https://accounts.google.com/signin/v2/challenge/pwd?continue=https%3A%2F%2Fmyaccount.google.com%2Fsigninoptions%2Fpassword%3Fhl%3Des&service=accountsettings&hl=es&sarp=1&scc=1&rart=ANgoxcfbrB2dE_sgedjxK5y1g-1xrTeakxNJsn5qhw_G5AMB7KWDk0RekDx6e8ZHF684fYcAPWxQfOccGnjt9jsd-4muBOG67g&TL=AKqFyY_vS8-VPhjWfFQBbnGqcJglQ5vM1s06o2bTPAcKmTNAOdapOa_rNvYUOZrN&flowName=GlifWebSignIn&cid=1&flowEntry=ServiceLogin">Email Us</a>
    </address>
  </div>

  <ul class="footer__nav">
    <li class="nav__item">
      <h2 class="nav__title">Categorias</h2>


      <ul class="nav__ul">
        <li>
          <a href="/pages/licores.html">Mi comisariato</a>
        </li>

        <li>
          <a href="#">Rio Store</a>
        </li>

        <li>
          <a href="#">Panaderia</a>
        </li>

        <li>
          <a href="#">Ferrisariato</a>
        </li>

      </ul>
    </li>



    <li class="nav__item">
      <h2 class="nav__title">Redes Sociales</h2>

      <ul class="nav__ul">
        <li>
          <a  href="">
              Instagram
             <img src="{% static 'img/Instagram.png' %}" alt="" width="45" height="30">
            </a>
        </li>

        <li>
          <a  href="https://www.facebook.com/cesar.sctg">
              Facebook
              <img src="{% static 'img/Facebook-Logo.png' %}" alt="" width="30" height="30">
            </a>
        </li>

        <li>
          <a  href="https://wa.me/593959989123">
              WhatsApp
              <img src="{% static 'img/WhatsApp.png' %}" alt="" width="45" height="30">
            </a>
        </li>
      </ul>
    </li>
  </ul>

  <div class="legal">
    <p>&copy; 2022 Something. All rights reserved.</p>
  </div>
</footer>

proyecto_final/templates/header.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light fixed-top " style="background-color: #ECF0F1; ">

        <div class="container-fluid">
          <a class="navbar-brand" href="#">
               <img src="{% static 'img/logo.png' %}" alt="" width="75" height="30">

          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto mb-2 mb-lg-0 ">
              <li class="nav-item lis">
                <a class="nav-link active" aria-current="page" href="{% url 'menu' %}">Principal</a>
              </li>
              <li class="nav-item lis">
                <a class="nav-link active" href="{% url 'Ventas:cliente' %}">Lineas</a>
              </li>
              <li class="nav-item lis">
                <a class="nav-link active" href="{% url 'producto' %}">Quienes Somos</a>
              </li>

              <li class="nav-item lis">
                <a class="nav-link active" href="{% url 'Ventas:postulante' %}">Trabaja con Nosotros</a>
              </li>
                <li class="nav-item lis">
                <a class="nav-link active" href="{% url 'Ventas:base' %}">Modulos</a>
              </li>
            </ul>
          </div>
        </div>
    </nav>

proyecto_final/templates/principal.html
{% extends 'base.html' %}
{% load static %}


<body>
{% block main %}
<header>
    {% block header %}
        {% include 'header.html' %}
    {% endblock %}
</header>
     <div class="imagen">
{#     <img src="{% static 'img/fond.jpeg' %}">#}
      <div class="bg-text container" >
        <h1 data-aos="fade-right">BIENVENIDOS A CCB</h1>
        <h2 data-aos="fade-up"
        data-aos-duration="3000">100% CALIDAD Y PRECIO</h2>
     </div>
 </div>
 <section class="container ">
  <h1 class="promocion1" data-aos="fade-right"
  data-aos-offset="300"
  data-aos-easing="ease-in-sine" data-aos-duration="3000">PROMOCIONES DEL PROGRAMA</h1>
  <div class="row row-cols-1 row-cols-md-3 g-4 klk">
    <div class="col" data-aos="zoom-out" data-aos-duration="3000">
      <div class="card h-100">
        <img src="./img/inicio.jpeg" class="img-fluid" alt="..." width="200px">
        <div class="card-body">
          <p>
            <a class="btn btn-primary" data-bs-toggle="collapse" href="#multiCollapseExample1" role="button" aria-expanded="false" aria-controls="multiCollapseExample1">Alimentos</a>
          </p>
        </div>
      </div>
    </div>
    <div class="col" data-aos="zoom-out" data-aos-duration="3000">
      <div class="card h-100">
        <img src="./img/inicio1.jpeg" class="img-fluid" alt="..." width="200px">
        <div class="card-body">
          <p>
            <a class="btn btn-primary" href="#" role="button">bebidas</a>
          </p>
        </div>
      </div>
    </div>
    <div class="col" data-aos="zoom-out" data-aos-duration="3000">
      <div class="card h-100">
        <img src="./img/inicio2.jpeg" class="img-fluid" alt="..." width="200px">
        <div class="card-body">
          <p>
            <a class="btn btn-primary" data-bs-toggle="collapse" href="#multiCollapseExample3" role="button" aria-expanded="false" aria-controls="multiCollapseExample3">Electrodomesticos</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<div class= "imagen2" data-aos="flip-left" data-aos-duration="3000"></div>
<div>
  <img src="{% static 'img/wave.svg' %}" alt="">
</div>

{% block footer%}
        {% include 'footer.html' %}
    {% endblock %}

<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script>
  AOS.init();
</script>

{% endblock %}

