proyecto_final/Ventas/urls.py
from django.contrib import admin
from django.urls import path

from .views.base.views import Base
from .views.linea.views import ClienteListView
from .views.productos.views import ProductosListView
from .views.postulante.views import PostulanteCreateViews
app_name="Ventas"
urlpatterns = [

    path('base', Base.as_view(), name="base"),
    path('cliente', ClienteListView.as_view(), name='cliente'),
    path('productos',ProductosListView.as_view(),name='productos'),
    path('postulante',PostulanteCreateViews.as_view(),name='postulante')

]

proyecto_final/proyecto_final/urls.py
from django.urls import path,include
from .views import Principal,Linea,Productos
from django.contrib import admin
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',Principal.as_view(),name="menu"),
    path('linea/',Linea.as_view(),name="linea"),
    path('producto',Productos.as_view(),name="producto"),

    path('sa/',include('Ventas.urls'))
]

proyecto_final/Ventas/models.py
from django.db import models

# Create your models here.

class Empresa(models.Model):
    nombre = models.CharField(max_length=50,verbose_name='Empresa',unique=True)
    contacto=models.CharField(max_length=50, blank=True, null=True)
    correo =  models.EmailField(max_length=100, blank=True, null=True)


    def __str__(self):
        return "{}".format(self.nombre)
    class Meta:
        verbose_name = 'Empresa'
        ordering = ('nombre',)

class Categoria(models.Model):
    descripcion = models.CharField(max_length=100,unique=True, blank=True, null=True)

    estado = models.BooleanField(default=True)
    fecha_creacion = models.DateTimeField(auto_now_add=False, auto_now=True)
    class Meta:
        verbose_name="Categoria"
        verbose_name_plural="Categoria"
        ordering = ['descripcion','id']
    def __str__(self):
        return "{} - {}".format(self.descripcion,self.id)

class Productos(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100, blank=False,null=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    estado = models.BooleanField(default=True)
    fecha_creacion = models.DateTimeField(auto_now_add=False, auto_now=True)
    class Meta:
        verbose_name="Productos"
        verbose_name_plural="Productos"
        ordering = ['nombre']
    def __str__(self):
        return "{} - {} - {}".format(self.categoria.descripcion,self.id,self.nombre)



class Postulante(models.Model):
    nombres = models.CharField(max_length=200, unique=True)
    apellidos = models.CharField(max_length=200, unique=True)
    email = models.CharField(max_length=100, unique=True)
    telefonos = models.CharField(max_length=50, blank=True, null=True)
    archivo = models.FileField(upload_to='usuar/media', blank=True, null=True)


    def __str__(self):
        return "{}".format(self.nombres)

    class Meta:
        verbose_name = "Postulante"
        verbose_name_plural = "Postulante"
        ordering = ('nombres',)

    def get_archivo(self):
        if self.archivo:
            return '{}{}'.format(settings.MEDIA_URL, self.archivo)
        return '{}{}'.format(settings.STATIC_URL, 'usuar/media')


proyecto_final/Ventas/forms.py
from django import forms
from django.forms import ModelForm

from Ventas.models import *


# class CategoriaForm(forms.ModelForm):
#     class Meta:
#         model = Categoria
#         fields = ['descripcion', 'estado']
#         widgets = {
#             'descripcion': forms.TextInput(attrs={
#                 'placeholder': 'Ingrese la linea de prooductos',
#                 'class': 'form-group',
#                 'required': True,
#             })
#
#         }
#
# class ProductosForm(forms.ModelForm):
#     class Meta:
#         model = Productos
#         fields = ['nombre', 'categoria', 'estado']
#         widgets = {
#             'nombre': forms.TextInput(attrs={
#                 'placeholder': 'Ingrese el nombre',
#                 'class': 'form-group',
#                 'required': True
#             }),
#
#             'categoria': forms.Select(attrs={
#                 'class': 'form-group',
#                 'required': True
#             }),
#         }


class PostulanteForm(ModelForm):
    class Meta:
        model = Postulante
        fields = '__all__'
        widgets = {
            'nombres': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese Nombres'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese Nombres'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese correo'}),
            'telefonos': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese de telefono'}),

        }




proyecto_final/Ventas/views/postulante/forms.py
from django.forms import ModelForm
from django import forms
from Ventas.models import Postulante


class PostulanteForm(ModelForm):
    class Meta:
        model = Postulante
        fields = '__all__'
        widgets = {
            'nombres': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese Nombres'}),
            'apellidos': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese Apellidos'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese correo'}),
            'telefonos': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ingrese de telefono'}),

        }



proyecto_final/Ventas/views.py

from django.shortcuts import render


proyecto_final/Ventas/views/base/views.py
from django.views.generic import TemplateView

class Base(TemplateView):
    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = "Menu Principal"
        context['url_anterior'] = '/'
        return context

proyecto_final/Ventas/views/linea/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from Ventas.models import Categoria,Productos,Empresa
class ClienteListView(ListView):
    template_name = "linea/list.html"
    model = Categoria
    context_object_name = 'lineas'
    paginate_by = 6
    #queryset = Cliente.objects.filter(estado=True)

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(nombres__icontains=query)
        else:
            return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'LISTADO DE LINEAS'
        context['query'] = self.request.GET.get("query") or ""
        return context

proyecto_final/Ventas/views/postulante/views.py
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView

from Ventas.views.postulante.forms import PostulanteForm
from Ventas.models import Categoria,Productos,Empresa,Postulante


class PostulanteCreateViews(CreateView):
    model = Postulante
    template_name = "postulante/form.html"
    form_class = PostulanteForm
    success_url = reverse_lazy('Ventas:postulante')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'TRABAJA CON NOSOTROS'
        context['action'] = 'add'
        return context

class Inicio(TemplateView):
    model = Empresa
    template_name = "principal.html"
    success_url = reverse_lazy('/')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Inicio'
        context['url_anterior'] = '/'
        context['nombre'] = Empresa.objects.values("nombre")
        context['contacto'] = Empresa.objects.values("contacto")
        context['correo'] = Empresa.objects.values("correo")
        return context

proyecto_final/Ventas/views/productos/views.py
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView
from Ventas.models import Categoria,Productos,Empresa
class ProductosListView(ListView):
    template_name = "productos/list.html"
    model = Productos
    context_object_name = 'productos'
    paginate_by = 6

    #queryset = Cliente.objects.filter(estado=True)

    def get_queryset(self):
        query = self.request.GET.get("query")
        print(query)
        if query:
            return self.model.objects.filter(nombres__icontains=query)
        else:
            return self.model.objects.all()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'LISTADO DE Productos'

        return context

proyecto_final/Ventas/templates/linea/list.html

{% load static %}


{% block titulo %}  Materia {% endblock %}

{% load static %}

{% block css %} <link rel="stylesheet" href="{% static 'css/formulario.css' %}"> {% endblock %}

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/header.css' %}">
<link rel="stylesheet" href="{% static 'css/estilos.css' %}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<style>
        body{
            background-color:black;
background-image:
radial-gradient(white, rgba(255,255,255,.2) 2px, transparent 40px),
radial-gradient(white, rgba(255,255,255,.15) 1px, transparent 30px),
radial-gradient(white, rgba(255,255,255,.1) 2px, transparent 40px),
radial-gradient(rgba(255,255,255,.4), rgba(255,255,255,.1) 2px, transparent 30px);
background-size: 550px 550px, 350px 350px, 250px 250px, 150px 150px;
background-position: 0 0, 40px 60px, 130px 270px, 70px 100px;
color: #171a4a;
        }
    </style>
 <header>
    {% block header %}
        {% include 'header.html' %}
    {% endblock %}
    {% block headcss %}
        <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    {% endblock %}
</header
</head>
<body>





{% block js %}
{#    <script src="{% static 'cliente/js/list.js' %}"></script>#}
{% endblock %}



    <div class="container py-5">

    </div>
    <div class="container py-5">

    <form class="container text-dark" method="post" action="" enctype="multipart/form-data">
       <div class="card card-primary">
            <div class="card-header bg-success">
                <h5 class="card-title text-center text-white">
                   {{ titulo }}
                </h5>
            </div>
            <div class="card-body row g-3">

                {% block controls %}

                {% endblock %}
            </div>

       <table class="table table-hover" id="consulta-est" border="1">


    <tr class="text-center">
        <th scope="col" style="width: 5%;">Codigo</th>
        <th scope="col" style="width: 20%;">Descripcion</th>
        <th scope="col" style="width: 10%;">Estados</th>
        <th scope="col" style="width: 30%;">Productos</th>



              <tbody class="detalle-est bg-light" id="detalle-est">
                {% for departamento in lineas %}
                <tr>
                    <td>{{departamento.id}}</td>

                    <td>{{departamento.descripcion}}</td>
                    <td>{{departamento.estado}}</td>
                    <td>

                       <a href="{% url 'Ventas:productos' %}" class="btn btn-primary" role="button" data-bs-toggle="button">Ver Productos</a>
                    </td>
                </tr>
                {% endfor %}

            </tbody>

          </table>

        </div>
    </form>




